### PR TITLE
Updating Systemd services to be more reliable

### PR DESCRIPTION
**Pull request by aesthernr**
Moving to using requires and after to make the ttyin and ttyout child services more reliable by ensuring the socat-smd11 service be up and running before they start. This also restarts the entire chain if any of the child processes are stopped for any reason. 

Moved the execstartpre to the child services rather the socat-smd11 parent to space out the turn up a little more.

### CODE REVIEW

**Comment by natecarlson** [comment]
I believe we actually want BindsTo instead of requires or partof, based on:
https://pychao.com/2021/02/24/difference-between-partof-and-bindsto-in-a-systemd-unit/

Did you actually see a difference moving the sleep to the start of the other AT services, versus the post of the main service? I went the way I did so automated starts will have the delay apply, but manually restarting that cat processes would not. If moving them to the start actually made a difference, I'm OK with that.

**Comment by aesthernr** [comment]
Yeah I think thats the most appropriate for the services. I'll update it.

**Comment by natecarlson** [comment]
> After playing around last two days between having sleep on ExecPre and ExecPost I see no difference, but having the requires or bindsTo ensures the tty fires up correctly after reboot.

I think I'll leave the sleep as an execpost then.. oddly, I have had zero problems with the daemon starting on modem bootup on the ones I've tried -- but I have had it fail to restart cleanly, which these also appear to cleanup for me.

> I suspect we could additionally update the at-telnet-daemon.service to using the following, I do not have it enabled on my modem but this would clean up the unit a bit. Requires=socat-smd11.service After=socat-smd11-from-ttyIN.service After=socat-smd11-to-ttyIN.service

Yup, that's what I was tending towards too!

I will edit the PR a bit and then merge - thanks much!

**Comment by aesthernr** [comment]
I wonder if it'll get into some weird circular dependency hell with that many binds to each other, would require some testing.

LGTM on the other updates.

**Comment by natecarlson** [comment]
> I wonder if it'll get into some weird circular dependency hell with that many binds to each other, would require some testing.

It shouldn't, as nothing else is declaring any relationship to the at-telnet-daemon.. but I'll make sure!

Thanks!!

**Pull request merged**
